; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
description = OnStepX

;[env:onstepx-maxesp3]
[env:onstepx-esp32]
platform = espressif32@6.4.0
board = esp32dev_16mb
board_build.flash_mode = dio
board_build.f_cpu = 240000000L
framework = arduino
build_flags =
    -D ONSTEPX
    -D ESP32
    -D SERIAL_BAUD_DEFAULT=115200
    -DCORE_DEBUG_LEVEL=0
monitor_speed = 115200
upload_speed = 921600
board_upload.erase_flash = true

lib_deps =
    adafruit/Adafruit BME280 Library@^2.3.0
    https://github.com/teemuatlut/TMCStepper.git
    https://github.com/hjd1964/TMC2209.git
    plerup/EspSoftwareSerial
    makuna/Rtc
    bblanchon/ArduinoJson @ ^6.21.0
    https://github.com/Hopperpop/Sgp4-Library.git
